// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef ACILAssistant_h
#define ACILAssistant_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *acilAssistantMainWindow;
#include <FL/Fl_Menu_Bar.H>
extern void GrayscaleImage_CB(Fl_Menu_*, void*);
extern void DicomDirectory_CB(Fl_Menu_*, void*);
extern void LabelMapImage_CB(Fl_Menu_*, void*);
extern void SessionFile_CB(Fl_Menu_*, void*);
extern void SaveSessionDataMenu_CB(Fl_Menu_*, void*);
extern void SaveLabelMapImageMenu_CB(Fl_Menu_*, void*);
extern void SaveRegionTypePointsMenu_CB(Fl_Menu_*, void*);
extern void Quit_CB(Fl_Menu_*, void*);
extern void paintBrushAndEraserMenu_CB(Fl_Menu_*, void*);
extern void queryOverlayMenu_CB(Fl_Menu_*, void*);
extern void lungMenu_CB(Fl_Menu_*, void*);
extern void paletteCounter_CB(Fl_Menu_*, void*);
extern void muscleMenu_CB(Fl_Menu_*, void*);
extern void leftLungRightLungMenu_CB(Fl_Menu_*, void*);
extern void lungLobesMenu_CB(Fl_Menu_*, void*);
extern void regionGrowingMenu_CB(Fl_Menu_*, void*);
#include "GLSliceView.h"
extern itk::GLSliceView< short, unsigned short > *sliceViewer;
#include <FL/Fl_Scrollbar.H>
extern void sliceSlider_CB(Fl_Scrollbar*, void*);
extern Fl_Scrollbar *sliceSlider;
#include <FL/Fl_Slider.H>
extern void opacitySlider_CB(Fl_Slider*, void*);
extern Fl_Slider *opacitySlider;
extern Fl_Menu_Item menu_Menu[];
void GrayscaleImage_CB( Fl_Widget*, void* );
void UpdateViewer();
void DicomDirectory_CB( Fl_Widget*, void* );
void InitializeViewer();
void sliceSlider_CB( Fl_Widget*, void* );
void LabelMapImage_CB( Fl_Widget*, void* );
void SessionFile_CB( Fl_Widget*, void* );
void opacitySlider_CB( Fl_Widget*, void* );
void paintBrushAndEraserMenu_CB( Fl_Widget*, void* );
void queryOverlayMenu_CB( Fl_Widget*, void* );
void lungMenu_CB( Fl_Widget*, void* );
void paletteCounter_CB(Fl_Widget*, void*);
void muscleMenu_CB( Fl_Widget*, void* );
void leftLungRightLungMenu_CB( Fl_Widget*, void* );
void lungLobesMenu_CB( Fl_Widget*, void* );
void regionGrowingMenu_CB( Fl_Widget*, void* );
void Quit_CB( Fl_Widget*, void* );
void clickSelect_CB( float x, float y, float z, float value );
void SaveLabelMapImageMenu_CB( Fl_Widget*, void* );
void SaveSessionDataMenu_CB( Fl_Widget*, void* );
void SaveRegionTypePointsMenu_CB( Fl_Widget*, void* );
#endif
