// This file was automatically generated by:
//  /Users/jross/Downloads/Slicer4/Slicer4-SuperBuild-Release/SlicerExecutionModel-build/GenerateCLP/bin/GenerateCLP --InputXML /Users/jross/Downloads/ChestImagingPlatformPrivate/CommandLineTools/GetTransformationSimilarityMetric/GetTransformationSimilarityMetric.xml --OutputCxx /Users/jross/Downloads/ChestImagingPlatformPrivate/CommandLineTools/GetTransformationSimilarityMetric/GetTransformationSimilarityMetricCLP.h
//
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
#include <map>

#include <sstream>

#include "tclap/CmdLine.h"
#include "ModuleProcessInformation.h"

#ifdef WIN32
#define Module_EXPORT __declspec(dllexport)
#else
#define Module_EXPORT 
#endif

#if defined(main) && !defined(REGISTER_TEST)
// If main defined as a preprocessor symbol, redefine it to the expected entry point.
#undef main
#define main ModuleEntryPoint

extern "C" {
  Module_EXPORT char *GetXMLModuleDescription();
  Module_EXPORT int ModuleEntryPoint(int, char*[]);
}
#endif

extern "C" {
Module_EXPORT char XMLModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<executable>\n"
"  <category>Examples</category>\n"
"  <title>GetTransformationSimilarityMetric</title>\n"
"  <description><![CDATA[This program calculates a similarity measure between 2 CT images in a region specified by a label map. It takes as input the 2 CT images and their corresponding label maps, and a transformation file, and appends the values of the similarity metric to an existing xml file if one is provided.]]></description>\n"
"  <version>0.0.1</version>\n"
"  <documentation-url>http://www.slicer.org/slicerWiki/index.php/Documentation/4.2/Modules/GetTransformationSimilarityMetric</documentation-url>\n"
"  <license>Slicer</license>\n"
"  <contributor> Applied Chest Imaging Laboratory, Brigham and women's hospital</contributor>\n"
"  <acknowledgements>This work was partially funded ...</acknowledgements>\n"
"  <parameters>\n"
"\n"
"    <string>\n"
"      <name>similarityMetric</name>\n"
"      <label>Similarity Metric</label>\n"
"      <channel>input</channel>\n"
"      <flag>v</flag>\n"
"      <longflag>--SimilarityMetric</longflag>\n"
"      <description><![CDATA[Similarity metric to be used. Choice between: MI (for mutual information), NMI (for normalized mutual information), and mean squares (msqr), NormalizedCorrelationImageToImageMetric (nc), gradient difference  (gd). Default: MI]]></description>\n"
"      <default>MI</default>\n"
"    </string>\n"
"\n"
"    <string>\n"
"      <name>fixedLabelmapFileName</name>\n"
"      <label>fixed LabelMap FileName</label>\n"
"      <channel>input</channel>\n"
"      <flag>f</flag>\n"
"      <longflag>--fixedLabelMapFileName</longflag>\n"
"      <description><![CDATA[fixed Image File Name]]></description>\n"
"      <default>q</default>\n"
"    </string> \n"
"\n"
"   <string>\n"
"      <name>movingLabelmapFileName</name>\n"
"      <label>moving LabelMap FileName</label>\n"
"      <channel>input</channel>\n"
"      <flag>m</flag>\n"
"      <longflag>--movingLabelMapFileName</longflag>\n"
"      <description><![CDATA[moving LabelMap FileName]]></description>\n"
"      <default>q</default>\n"
"    </string>\n"
"\n"
"   <string>\n"
"      <name>fixedCTFileName</name>\n"
"      <label>fixed CT FileName</label>\n"
"      <channel>input</channel>\n"
"      <flag>g</flag>\n"
"      <longflag>--fixedCTFileName</longflag>\n"
"      <description><![CDATA[fixed CT File Name]]></description>\n"
"      <default>e</default>\n"
"    </string>   \n"
"    <string>\n"
"      <name>movingCTFileName</name>\n"
"      <label>moving CT FileName</label>\n"
"      <channel>input</channel>\n"
"      <flag>a</flag>\n"
"      <longflag>--movingCTFileName</longflag>\n"
"      <description><![CDATA[moving CT FileName]]></description>\n"
"      <default>e</default>\n"
"    </string>\n"
"    <string>\n"
"      <name>movingImageID</name>\n"
"      <label>moving Image subject ID</label>\n"
"      <channel>input</channel>\n"
"      <flag>s</flag>\n"
"      <longflag>--movingImageID</longflag>\n"
"      <description><![CDATA[Moving Image subject ID. If not specified, the subject ID will be automatically extracted from the file path]]></description>\n"
"      <default>q</default>\n"
"    </string>   \n"
"    <string>\n"
"      <name>fixedImageID</name>\n"
"      <label>Fixed Image subject ID</label>\n"
"      <channel>input</channel>\n"
"      <flag>u</flag>\n"
"      <longflag>--fixedImageID</longflag>\n"
"      <description><![CDATA[Fixed Image subject ID. If not specified, the subject ID will be automatically extracted from the file path]]></description>\n"
"      <default>q</default>\n"
"    </string> \n"
"    <float>\n"
"      <name>downsampleFactor</name>\n"
"      <label>downsample Factor</label>\n"
"      <channel>input</channel>\n"
"      <flag>d</flag>\n"
"      <longflag>--degrees</longflag>\n"
"      <description><![CDATA[downsampleFactor]]></description>\n"
"      <default>1.0</default>\n"
"    </float>  \n"
"<integer-vector>\n"
"      <name>typeVecArg</name>\n"
"      <longflag>--typeVec</longflag>\n"
"      <flag>c</flag>\n"
"      <label>typeVec</label>\n"
"      <description><![CDATA[Specify a region in a region-type pair you want to crop. This flag should be used together with the -typePair flag]]></description>\n"
"</integer-vector>\n"
"\n"
"<integer-vector>\n"
"      <name>typePairVecArg</name>\n"
"      <longflag>--typePairVec</longflag>\n"
"      <flag>w</flag>\n"
"      <label>typePairVec</label>\n"
"      <description><![CDATA[Specify a type in a region type pair you want to crop. This flag should be used together with the egionPair flag]]></description>\n"
"</integer-vector>\n"
"\n"
"<integer-vector>\n"
"      <name>regionPairVecArg</name>\n"
"      <longflag>regionPairVec</longflag>\n"
"      <flag>b</flag>\n"
"      <label>regionPairVec</label>\n"
"      <description><![CDATA[Specify a region in a region type pair you want to crop. This flag should be used together with the -typePair flag]]></description>\n"
"</integer-vector>\n"
"\n"
"\n"
"    <string>\n"
"      <name>inputTransformFileName</name>\n"
"      <label>input Transform FileName</label>\n"
"      <channel>input</channel>\n"
"      <flag>q</flag>\n"
"      <longflag>--inputTransform</longflag>\n"
"      <description><![CDATA[Input transform file name]]></description>\n"
"      <default>q</default>\n"
"    </string>   \n"
"<integer-vector>\n"
"      <name>regionVecArg</name>\n"
"      <longflag>--regionVec</longflag>\n"
"      <flag>r</flag>\n"
"      <label>regionVec</label>\n"
"      <description><![CDATA[Specify a region in a region-type pair you want to crop. This flag should be used together with the -typePair flag]]></description>\n"
"</integer-vector>\n"
"\n"
" \n"
"\n"
"\n"
"  </parameters>\n"
"</executable>\n"
;

}

void
splitString (const std::string &text,
             const std::string &separators,
             std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  std::string::size_type start = text.find_first_not_of(separators);
  while (start < n)
    {
    std::string::size_type stop = text.find_first_of(separators, start);
    if (stop > n) stop = n;
    words.push_back(text.substr(start, stop - start));
    start = text.find_first_not_of(separators, stop+1);
    }
}

void
splitFilenames (const std::string &text,
                std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  bool quoted;
  std::string comma(",");
  std::string quote("\"");
  std::string::size_type start = text.find_first_not_of(comma);
  while (start < n)
    {
    quoted = false;
    std::string::size_type startq = text.find_first_of(quote, start);
    std::string::size_type stopq = text.find_first_of(quote, startq+1);
    std::string::size_type stop = text.find_first_of(comma, start);
    if (stop > n) stop = n;
    if (startq != std::string::npos && stopq != std::string::npos)
      {
      while (startq < stop && stop < stopq && stop != n)
         {
         quoted = true;
         stop = text.find_first_of(comma, stop+1);
         if (stop > n) stop = n;
         }
      }
    if (!quoted)
      {
      words.push_back(text.substr(start, stop - start));
      }
    else
      {
      words.push_back(text.substr(start+1, stop - start-2));
      }
    start = text.find_first_not_of(comma, stop+1);
    }
}

char *GetXMLModuleDescription()
{
   return XMLModuleDescription;
}

#define GENERATE_LOGO
#define GENERATE_XML \
  if (argc >= 2 && (strcmp(argv[1],"--xml") == 0)) \
    { \
    std::cout << GetXMLModuleDescription(); \
    return EXIT_SUCCESS; \
    }
#define GENERATE_TCLAP \
    std::string similarityMetric = "MI"; \
    std::string fixedLabelmapFileName = "q"; \
    std::string movingLabelmapFileName = "q"; \
    std::string fixedCTFileName = "e"; \
    std::string movingCTFileName = "e"; \
    std::string movingImageID = "q"; \
    std::string fixedImageID = "q"; \
    float downsampleFactor = 1.0; \
    std::string typeVecArgTemp; \
    std::vector<int> typeVecArg; \
    std::string typePairVecArgTemp; \
    std::vector<int> typePairVecArg; \
    std::string regionPairVecArgTemp; \
    std::vector<int> regionPairVecArg; \
    std::string inputTransformFileName = "q"; \
    std::string regionVecArgTemp; \
    std::vector<int> regionVecArg; \
    bool echoSwitch = false; \
    bool xmlSwitch = false; \
    std::string processInformationAddressString = "0"; \
    std::string returnParameterFile; \
    std::string fullDescription("Description: "); \
    fullDescription += "This program calculates a similarity measure between 2 CT images in a region specified by a label map. It takes as input the 2 CT images and their corresponding label maps, and a transformation file, and appends the values of the similarity metric to an existing xml file if one is provided."; \
    if (!std::string("Applied Chest Imaging Laboratory, Brigham and women's hospital").empty()) \
      { \
      fullDescription += "\nAuthor(s): Applied Chest Imaging Laboratory, Brigham and women's hospital"; \
      } \
    if (!std::string("This work was partially funded ...").empty()) \
      { \
      fullDescription += "\nAcknowledgements: This work was partially funded ..."; \
      } \
    TCLAP::CmdLine commandLine (fullDescription, \
       ' ', \
      "0.0.1" ); \
 \
      std::ostringstream msg; \
    msg.str("");msg << "Similarity metric to be used. Choice between: MI (for mutual information), NMI (for normalized mutual information), and mean squares (msqr), NormalizedCorrelationImageToImageMetric (nc), gradient difference  (gd). Default: MI (default: " << similarityMetric << ")"; \
    TCLAP::ValueArg<std::string > similarityMetricArg("v", "SimilarityMetric", msg.str(), 0, similarityMetric, "std::string", commandLine); \
 \
    msg.str("");msg << "fixed Image File Name (default: " << fixedLabelmapFileName << ")"; \
    TCLAP::ValueArg<std::string > fixedLabelmapFileNameArg("f", "fixedLabelMapFileName", msg.str(), 0, fixedLabelmapFileName, "std::string", commandLine); \
 \
    msg.str("");msg << "moving LabelMap FileName (default: " << movingLabelmapFileName << ")"; \
    TCLAP::ValueArg<std::string > movingLabelmapFileNameArg("m", "movingLabelMapFileName", msg.str(), 0, movingLabelmapFileName, "std::string", commandLine); \
 \
    msg.str("");msg << "fixed CT File Name (default: " << fixedCTFileName << ")"; \
    TCLAP::ValueArg<std::string > fixedCTFileNameArg("g", "fixedCTFileName", msg.str(), 0, fixedCTFileName, "std::string", commandLine); \
 \
    msg.str("");msg << "moving CT FileName (default: " << movingCTFileName << ")"; \
    TCLAP::ValueArg<std::string > movingCTFileNameArg("a", "movingCTFileName", msg.str(), 0, movingCTFileName, "std::string", commandLine); \
 \
    msg.str("");msg << "Moving Image subject ID. If not specified, the subject ID will be automatically extracted from the file path (default: " << movingImageID << ")"; \
    TCLAP::ValueArg<std::string > movingImageIDArg("s", "movingImageID", msg.str(), 0, movingImageID, "std::string", commandLine); \
 \
    msg.str("");msg << "Fixed Image subject ID. If not specified, the subject ID will be automatically extracted from the file path (default: " << fixedImageID << ")"; \
    TCLAP::ValueArg<std::string > fixedImageIDArg("u", "fixedImageID", msg.str(), 0, fixedImageID, "std::string", commandLine); \
 \
    msg.str("");msg << "downsampleFactor (default: " << downsampleFactor << ")"; \
    TCLAP::ValueArg<float > downsampleFactorArg("d", "degrees", msg.str(), 0, downsampleFactor, "float", commandLine); \
 \
    msg.str("");msg << "Specify a region in a region-type pair you want to crop. This flag should be used together with the -typePair flag";    TCLAP::ValueArg<std::string > typeVecArgArg("c", "typeVec", msg.str(), 0, typeVecArgTemp, "std::vector<int>", commandLine); \
 \
    msg.str("");msg << "Specify a type in a region type pair you want to crop. This flag should be used together with the egionPair flag";    TCLAP::ValueArg<std::string > typePairVecArgArg("w", "typePairVec", msg.str(), 0, typePairVecArgTemp, "std::vector<int>", commandLine); \
 \
    msg.str("");msg << "Specify a region in a region type pair you want to crop. This flag should be used together with the -typePair flag";    TCLAP::ValueArg<std::string > regionPairVecArgArg("b", "regionPairVec", msg.str(), 0, regionPairVecArgTemp, "std::vector<int>", commandLine); \
 \
    msg.str("");msg << "Input transform file name (default: " << inputTransformFileName << ")"; \
    TCLAP::ValueArg<std::string > inputTransformFileNameArg("q", "inputTransform", msg.str(), 0, inputTransformFileName, "std::string", commandLine); \
 \
    msg.str("");msg << "Specify a region in a region-type pair you want to crop. This flag should be used together with the -typePair flag";    TCLAP::ValueArg<std::string > regionVecArgArg("r", "regionVec", msg.str(), 0, regionVecArgTemp, "std::vector<int>", commandLine); \
 \
    msg.str("");msg << "Echo the command line arguments (default: " << echoSwitch << ")"; \
    TCLAP::SwitchArg echoSwitchArg("", "echo", msg.str(), commandLine, echoSwitch); \
 \
    msg.str("");msg << "Produce xml description of command line arguments (default: " << xmlSwitch << ")"; \
    TCLAP::SwitchArg xmlSwitchArg("", "xml", msg.str(), commandLine, xmlSwitch); \
 \
    msg.str("");msg << "Address of a structure to store process information (progress, abort, etc.). (default: " << processInformationAddressString << ")"; \
    TCLAP::ValueArg<std::string > processInformationAddressStringArg("", "processinformationaddress", msg.str(), 0, processInformationAddressString, "std::string", commandLine); \
 \
    msg.str("");msg << "Filename in which to write simple return parameters (int, float, int-vector, etc.) as opposed to bulk return parameters (image, geometry, transform, measurement, table).";    TCLAP::ValueArg<std::string > returnParameterFileArg("", "returnparameterfile", msg.str(), 0, returnParameterFile, "std::string", commandLine); \
 \
try \
  { \
    /* Build a map of flag aliases to the true flag */ \
    std::map<std::string,std::string> flagAliasMap; \
    std::map<std::string,std::string> deprecatedFlagAliasMap; \
    std::map<std::string,std::string> longFlagAliasMap; \
    std::map<std::string,std::string> deprecatedLongFlagAliasMap; \
    /* Remap flag aliases to the true flag */ \
    std::vector<std::string> targs; \
    std::map<std::string,std::string>::iterator ait; \
    std::map<std::string,std::string>::iterator dait; \
    size_t ac; \
    for (ac=0; ac < static_cast<size_t>(argc); ++ac)  \
       {  \
       if (strlen(argv[ac]) == 2 && argv[ac][0]=='-') \
         { \
         /* short flag case */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         ait = flagAliasMap.find(tflag); \
         dait = deprecatedFlagAliasMap.find(tflag); \
         if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
           { \
           if (ait != flagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("-" + (*ait).second); \
             } \
           else if (dait != deprecatedFlagAliasMap.end()) \
             { \
             std::cout << "Flag \"" << argv[ac] << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("-" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]=='-') \
         { \
         /* long flag case */ \
         std::string tflag(argv[ac], 2, strlen(argv[ac])-2); \
         ait = longFlagAliasMap.find(tflag); \
         dait = deprecatedLongFlagAliasMap.find(tflag); \
         if (ait != longFlagAliasMap.end() || dait != deprecatedLongFlagAliasMap.end()) \
           { \
           if (ait != longFlagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("--" + (*ait).second); \
             } \
           else if (dait != deprecatedLongFlagAliasMap.end()) \
             { \
             std::cout << "Long flag \"" << argv[ac] << "\" is deprecated. Please use long flag \"--" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("--" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]!='-') \
         { \
         /* short flag case where multiple flags are given at once ala */ \
         /* "ls -ltr" */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         std::string rflag("-"); \
         for (std::string::size_type fi=0; fi < tflag.size(); ++fi) \
           { \
           std::string tf(tflag, fi, 1); \
           ait = flagAliasMap.find(tf); \
           dait = deprecatedFlagAliasMap.find(tf); \
           if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
             { \
             if (ait != flagAliasMap.end()) \
               { \
               /* remap the flag */ \
               rflag += (*ait).second; \
               } \
             else if (dait != deprecatedFlagAliasMap.end()) \
               { \
               std::cout << "Flag \"-" << tf << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
               /* remap the flag */ \
               rflag += (*dait).second; \
               } \
             } \
           else \
             { \
             rflag += tf; \
             } \
           } \
         targs.push_back(rflag); \
         } \
       else \
         { \
         /* skip the argument without remapping (this is the case for any */ \
         /* arguments for flags */ \
         targs.push_back(argv[ac]); \
         } \
       } \
 \
   /* Remap args to a structure that CmdLine::parse() can understand*/ \
   std::vector<char*> vargs; \
   for (ac = 0; ac < targs.size(); ++ac) \
     {  \
     vargs.push_back(const_cast<char *>(targs[ac].c_str())); \
     } \
    commandLine.parse ( vargs.size(), (char**) &(vargs[0]) ); \
    similarityMetric = similarityMetricArg.getValue(); \
    fixedLabelmapFileName = fixedLabelmapFileNameArg.getValue(); \
    movingLabelmapFileName = movingLabelmapFileNameArg.getValue(); \
    fixedCTFileName = fixedCTFileNameArg.getValue(); \
    movingCTFileName = movingCTFileNameArg.getValue(); \
    movingImageID = movingImageIDArg.getValue(); \
    fixedImageID = fixedImageIDArg.getValue(); \
    downsampleFactor = downsampleFactorArg.getValue(); \
    typeVecArgTemp = typeVecArgArg.getValue(); \
    typePairVecArgTemp = typePairVecArgArg.getValue(); \
    regionPairVecArgTemp = regionPairVecArgArg.getValue(); \
    inputTransformFileName = inputTransformFileNameArg.getValue(); \
    regionVecArgTemp = regionVecArgArg.getValue(); \
    echoSwitch = echoSwitchArg.getValue(); \
    xmlSwitch = xmlSwitchArg.getValue(); \
    processInformationAddressString = processInformationAddressStringArg.getValue(); \
    returnParameterFile = returnParameterFileArg.getValue(); \
      { /* Assignment for typeVecArg */ \
      std::vector<std::string> words; \
      std::string sep(","); \
      splitString(typeVecArgTemp, sep, words); \
      for (unsigned int _j = 0; _j < words.size(); _j++) \
        { \
        typeVecArg.push_back(atoi(words[_j].c_str())); \
        } \
      } \
      { /* Assignment for typePairVecArg */ \
      std::vector<std::string> words; \
      std::string sep(","); \
      splitString(typePairVecArgTemp, sep, words); \
      for (unsigned int _j = 0; _j < words.size(); _j++) \
        { \
        typePairVecArg.push_back(atoi(words[_j].c_str())); \
        } \
      } \
      { /* Assignment for regionPairVecArg */ \
      std::vector<std::string> words; \
      std::string sep(","); \
      splitString(regionPairVecArgTemp, sep, words); \
      for (unsigned int _j = 0; _j < words.size(); _j++) \
        { \
        regionPairVecArg.push_back(atoi(words[_j].c_str())); \
        } \
      } \
      { /* Assignment for regionVecArg */ \
      std::vector<std::string> words; \
      std::string sep(","); \
      splitString(regionVecArgTemp, sep, words); \
      for (unsigned int _j = 0; _j < words.size(); _j++) \
        { \
        regionVecArg.push_back(atoi(words[_j].c_str())); \
        } \
      } \
  } \
catch ( TCLAP::ArgException e ) \
  { \
  std::cerr << "error: " << e.error() << " for arg " << e.argId() << std::endl; \
  return ( EXIT_FAILURE ); \
  }
#define GENERATE_ECHOARGS \
if (echoSwitch) \
{ \
std::cout << "Command Line Arguments" << std::endl; \
std::cout << "    similarityMetric: " << similarityMetric << std::endl; \
std::cout << "    fixedLabelmapFileName: " << fixedLabelmapFileName << std::endl; \
std::cout << "    movingLabelmapFileName: " << movingLabelmapFileName << std::endl; \
std::cout << "    fixedCTFileName: " << fixedCTFileName << std::endl; \
std::cout << "    movingCTFileName: " << movingCTFileName << std::endl; \
std::cout << "    movingImageID: " << movingImageID << std::endl; \
std::cout << "    fixedImageID: " << fixedImageID << std::endl; \
std::cout << "    downsampleFactor: " << downsampleFactor << std::endl; \
std::cout << "    typeVecArg: "; \
for (unsigned int _i =0; _i < typeVecArg.size(); _i++) \
{ \
std::cout << typeVecArg[_i] << ", "; \
} \
std::cout <<std::endl; \
std::cout << "    typePairVecArg: "; \
for (unsigned int _i =0; _i < typePairVecArg.size(); _i++) \
{ \
std::cout << typePairVecArg[_i] << ", "; \
} \
std::cout <<std::endl; \
std::cout << "    regionPairVecArg: "; \
for (unsigned int _i =0; _i < regionPairVecArg.size(); _i++) \
{ \
std::cout << regionPairVecArg[_i] << ", "; \
} \
std::cout <<std::endl; \
std::cout << "    inputTransformFileName: " << inputTransformFileName << std::endl; \
std::cout << "    regionVecArg: "; \
for (unsigned int _i =0; _i < regionVecArg.size(); _i++) \
{ \
std::cout << regionVecArg[_i] << ", "; \
} \
std::cout <<std::endl; \
std::cout << "    echoSwitch: " << echoSwitch << std::endl; \
std::cout << "    xmlSwitch: " << xmlSwitch << std::endl; \
std::cout << "    processInformationAddressString: " << processInformationAddressString << std::endl; \
std::cout << "    returnParameterFile: " << returnParameterFile << std::endl; \
}
#define GENERATE_ProcessInformationAddressDecoding \
ModuleProcessInformation *CLPProcessInformation = 0; \
if (processInformationAddressString != "") \
{ \
sscanf(processInformationAddressString.c_str(), "%p", &CLPProcessInformation); \
}
#define PARSE_ARGS GENERATE_LOGO;GENERATE_XML;GENERATE_TCLAP;GENERATE_ECHOARGS;GENERATE_ProcessInformationAddressDecoding;
